"""One-command runner skeleton that emits committed text/SVG outputs."""

from __future__ import annotations

import argparse
from pathlib import Path

from experiments.plots import PLOTS_DIR, svg_template
from experiments.report import REPORT_CSV, REPORT_MD
from experiments.runner import planned_baselines, synthetic_rows
from experiments.scenarios import SCENARIOS


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run all baselines and scenarios.")
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--out-dir", default="results")
    return parser


def _write_outputs() -> None:
    rows = synthetic_rows()
    REPORT_CSV.parent.mkdir(parents=True, exist_ok=True)
    csv_lines = [
        "baseline,scenario,attack_success_rate,cost_leakage_tokens,false_reject_rate,throttle_rate,p50_ms,p95_ms"
    ]
    for row in rows:
        csv_lines.append(
            f"{row.baseline},{row.scenario},{row.attack_success_rate:.2f},{row.cost_leakage_tokens},"
            f"{row.false_reject_rate:.2f},{row.throttle_rate:.2f},{row.p50_ms},{row.p95_ms}"
        )
    REPORT_CSV.write_text("\n".join(csv_lines) + "\n", encoding="utf-8")

    REPORT_MD.write_text(
        "# Results Report\n\n"
        "Generated by `python -m scripts.run_all` using deterministic stage0 synthetic data.\n\n"
        f"Baselines: {', '.join(planned_baselines())}\n\n"
        f"Scenarios: {', '.join(SCENARIOS.keys())}\n",
        encoding="utf-8",
    )

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    (PLOTS_DIR / "attack_success.svg").write_text(svg_template("Attack Success"), encoding="utf-8")
    (PLOTS_DIR / "cost_leakage.svg").write_text(svg_template("Cost Leakage"), encoding="utf-8")
    (PLOTS_DIR / "latency.svg").write_text(svg_template("Latency"), encoding="utf-8")


def main() -> None:
    args = build_parser().parse_args()
    print(f"[run_all] seed={args.seed} out_dir={Path(args.out_dir)}")
    print(f"[run_all] baselines={','.join(planned_baselines())}")
    print(f"[run_all] scenarios={','.join(SCENARIOS)}")
    _write_outputs()
    print("[run_all] wrote results/report.csv, results/report.md, results/plots/*.svg")


if __name__ == "__main__":
    main()
